name: Check worktree clean
description: Fail if there's uncommitted changes in git worktree.

runs:
  using: "composite"
  steps:
      - name: Checkout Scripts Repo
        uses: actions/checkout@v3
        with:
          path: ci-scripts
          repository: pulumi/scripts

      - name: Check worktree clean
        shell: bash
        run: ./ci-scripts/ci/check-worktree-is-clean

      - run: git status --porcelain
        shell: bash
